### PR TITLE
Add banner data migration scripts

### PR DESCRIPTION
**Pull request by mateoclarke**
You can see my notebook here:
https://github.com/cityofaustin/transportation-data-tech/blob/0cc727f44f8f570eccd4a2fd0bd9386e82b2d28f/dev/data_cleaning/banner_data_migration/banner_data.ipynb

Very open to feedback on better Python 🐍 tricks.

I enjoyed playing around with Jupyter notebook and pandas for this type of data munging. It felt like a nice environment for getting quick feedback on whether dataframes were getting updated properly. I also liked how you can use the Markdown blocks to add documentation. I think this makes it a little more approachable that comment lines in code for non-programmers. It also had some negatives. I felt like I forgot save a couple times and that burned me. It's cool how Github renders notebooks but I also wish it were easier to review code line by line in a PR.

Anyways, we'll probably need to revisit this for the historical import but @dianamartin said that was a lower priority for the banners folks.

### CODE REVIEW

**Comment by johnclary** [comment]
Looks good to me, but, yeah it's hard to review your PR since it's in the notebook config. 

Since you're going to the trouble of using pandas and putting this in a notebook, it would have been helpful to see data printed out at certain steps. 

Small bit of feedback is that is that rather than explicitly checking types, like this:
```python
if type(df_reservations["Permit Number"][i]) == float and math.isnan(df_reservations["Permit Number"][i]):
    permit_number = None
    parent_id = None
```
it's more pythonic [duck type](http://www.voidspace.org.uk/python/articles/duck_typing.shtml) and catch and exception. So you'd do something like:

```python
try:
    float(df_reservations["Permit Number"][i])
    permit_number = None
    parent_id = None
except:
    pass
```

otherwise, looks good to me. tbh, i'm not the biggest fan of pandas. it makes sense for data exploration and when you want to present data visually in a notebook, or for one-off tasks. but when it's used for serializing data and manipulating lists and dicts, well, standard python library is already great  for that. that said, i've barely used pandas and it seems really handy.

**Comment by mateoclarke** [comment]
haha, I did have some data printing but Joey suggested I remove any `print()` statements to make the notebook look more clean. And he had a good point that if the data was sensitive, it shouldn't get printed in a public repo.

Thanks for the suggestion about a more pythonic way to do type checking. What you suggested didn't work on first try but I'll give it some more time when I log back in tomorrow.

I remember you saying in the past that pandas is overkill for most things. For importing the excel file, it was the first thing Google recommended. And it was pretty googlable in general. Will consider doing tasks like this in the future without it.

**Comment by johnclary** [comment]
really good point about not printing sensitive data. i didn't test the code or fully understand what you were trying to do there, so let me know if you can't resolve it. there are definitely times where writing succinct code conflict with the try/except paradigm. 

importing xlsx files is a strong use case for pandas. there are other libraries for this (which pandas might use), but i'm in favor of the path of least resistance for things like this. Just don't want you to miss out on learning fun standard lib stuff like opening files and parsing csvs.

**Comment by mateoclarke** [comment]
With my last commit, I think this PR is good to merge to master. Thanks for the feedback y'all...

**Pull request merged**
